services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - node-network

  nginx:
    image: nginx:alpine
    user: root
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/ssl
    ports:
      - '8080:80'
      - '443:443'
    depends_on:
      - node
    restart: unless-stopped
    networks:
      - node-network

networks:
  node-network:
